version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/core/static
      - media_volume:/home/app/web/core/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/core/static
      - media_volume:/home/app/web/core/static
    ports:
      - 1337:80
    depends_on:
      - web

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./app
    command: celery -A hello_django worker --loglevel=info
    depends_on:
      - web
      - redis
    env_file:
      - ./.env.prod
    volumes:
      - ./app:/usr/src/app/

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
